In [29]:
import pandas as pd

In [30]:
states = pd.read_csv(
    'https://www2.census.gov/geo/docs/reference/codes2020/national_state2020.txt',
    sep='|', dtype=str
)
states = states[['STATE_NAME', 'STATEFP']]
states.columns = [ 'state_name', 'state_fp']

In [31]:
benef = pd.read_csv("./data/DE1_0_2008_Beneficiary_Summary_File_Sample_1.csv")
benef.columns

Index(['DESYNPUF_ID', 'BENE_BIRTH_DT', 'BENE_DEATH_DT', 'BENE_SEX_IDENT_CD',
       'BENE_RACE_CD', 'BENE_ESRD_IND', 'SP_STATE_CODE', 'BENE_COUNTY_CD',
       'BENE_HI_CVRAGE_TOT_MONS', 'BENE_SMI_CVRAGE_TOT_MONS',
       'BENE_HMO_CVRAGE_TOT_MONS', 'PLAN_CVRG_MOS_NUM', 'SP_ALZHDMTA',
       'SP_CHF', 'SP_CHRNKIDN', 'SP_CNCR', 'SP_COPD', 'SP_DEPRESSN',
       'SP_DIABETES', 'SP_ISCHMCHT', 'SP_OSTEOPRS', 'SP_RA_OA', 'SP_STRKETIA',
       'MEDREIMB_IP', 'BENRES_IP', 'PPPYMT_IP', 'MEDREIMB_OP', 'BENRES_OP',
       'PPPYMT_OP', 'MEDREIMB_CAR', 'BENRES_CAR', 'PPPYMT_CAR'],
      dtype='str')

In [32]:
benef_cols = {
    'DESYNPUF_ID': 'bene_id',
    'BENE_BIRTH_DT': 'birth_dt',
    'BENE_DEATH_DT': 'death_dt',
    'BENE_SEX_IDENT_CD': 'sex',
    'BENE_RACE_CD': 'race',
    'BENE_ESRD_IND': 'esrd',
    'SP_STATE_CODE': 'state',
    'BENE_COUNTY_CD': 'county',
    'BENE_HI_CVRAGE_TOT_MONS': 'hi_mos',
    'BENE_SMI_CVRAGE_TOT_MONS': 'smi_mos',
    'BENE_HMO_CVRAGE_TOT_MONS': 'hmo_mos',
    'PLAN_CVRG_MOS_NUM': 'plan_mos',
    'SP_ALZHDMTA': 'alzheimer',
    'SP_CHF': 'chf',
    'SP_CHRNKIDN': 'ckd',
    'SP_CNCR': 'cancer',
    'SP_COPD': 'copd',
    'SP_DEPRESSN': 'depression',
    'SP_DIABETES': 'diabetes',
    'SP_ISCHMCHT': 'ischemic_heart',
    'SP_OSTEOPRS': 'osteoporosis',
    'SP_RA_OA': 'arthritis',
    'SP_STRKETIA': 'stroke_tia',
    'MEDREIMB_IP': 'ip_reimb',
    'BENRES_IP': 'ip_bene_resp',
    'MEDREIMB_CAR': 'car_reimb',
    'BENRES_CAR': 'car_bene_resp',
    'PPPYMT_CAR': 'car_ppp_pmt',
}
benef.rename(columns=benef_cols, inplace=True)

In [33]:
print(benef.columns)
states.head(3)

Index(['bene_id', 'birth_dt', 'death_dt', 'sex', 'race', 'esrd', 'state',
       'county', 'hi_mos', 'smi_mos', 'hmo_mos', 'plan_mos', 'alzheimer',
       'chf', 'ckd', 'cancer', 'copd', 'depression', 'diabetes',
       'ischemic_heart', 'osteoporosis', 'arthritis', 'stroke_tia', 'ip_reimb',
       'ip_bene_resp', 'PPPYMT_IP', 'MEDREIMB_OP', 'BENRES_OP', 'PPPYMT_OP',
       'car_reimb', 'car_bene_resp', 'car_ppp_pmt'],
      dtype='str')

  state_name state_fp
0    Alabama       01
1     Alaska       02
2    Arizona       04

In [34]:
benef['sex'] = benef['sex'].map({1:'M', 2:'F'})
benef['state'] = benef['state'].astype(str)
benef = benef.merge(states, left_on='state', right_on='state_fp', how='left')
benef = benef.drop(['state_fp', 'county', 'race' ],axis=1)
benef.head(3)

,bene_id,birth_dt,death_dt,sex,esrd,state,hi_mos,smi_mos,hmo_mos,plan_mos,...,ip_reimb,ip_bene_resp,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,car_reimb,car_bene_resp,car_ppp_pmt,state_name
0,00013D2EFD8E45D1,19230501,NaN,M,0,26,12,12,12,12,...,0.0,0.0,0.0,50.0,10.0,0.0,0.0,0.0,0.0,Michigan
1,00016F745862898F,19430101,NaN,M,0,39,12,12,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,700.0,240.0,0.0,Ohio
2,0001FDD721E223DC,19360901,NaN,F,0,39,12,12,0,12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ohio

# Claims section

In [35]:
claims1 = pd.read_csv('./data/DE1_0_2008_to_2010_Carrier_Claims_Sample_1A.csv')
claims2 = pd.read_csv('./data/DE1_0_2008_to_2010_Carrier_Claims_Sample_1B.csv')
print(claims1.sample(4))
print(claims2.sample(4))
#%[jupynvim:cell-sep]

/var/folders/42/kvbt_f651c7ch5cl9ld5g_f40000gp/T/ipykernel_85217/668998214.py:1: DtypeWarning: Columns (0: ICD9_DGNS_CD_6, 1: ICD9_DGNS_CD_7, 2: ICD9_DGNS_CD_8, 3: HCPCS_CD_9, 4: HCPCS_CD_10, 5: HCPCS_CD_11, 6: HCPCS_CD_12, 7: HCPCS_CD_13, 8: LINE_ICD9_DGNS_CD_7, 9: LINE_ICD9_DGNS_CD_8, 10: LINE_ICD9_DGNS_CD_9, 11: LINE_ICD9_DGNS_CD_10, 12: LINE_ICD9_DGNS_CD_11, 13: LINE_ICD9_DGNS_CD_12, 14: LINE_ICD9_DGNS_CD_13) have mixed types. Specify dtype option on import or set low_memory=False.
  claims1 = pd.read_csv('./data/DE1_0_2008_to_2010_Carrier_Claims_Sample_1A.csv')

In [27]:
benef1_claims = claims1.rename(columns={'DESYNPUF_ID':'bene_id'})
benef1_claims = benef.merge(right=benef1_claims, on='bene_id', how='left')
benef1_claims.sample(3)

,bene_id,birth_dt,death_dt,sex,esrd,state,hi_mos,smi_mos,hmo_mos,plan_mos,...,LINE_ICD9_DGNS_CD_4,LINE_ICD9_DGNS_CD_5,LINE_ICD9_DGNS_CD_6,LINE_ICD9_DGNS_CD_7,LINE_ICD9_DGNS_CD_8,LINE_ICD9_DGNS_CD_9,LINE_ICD9_DGNS_CD_10,LINE_ICD9_DGNS_CD_11,LINE_ICD9_DGNS_CD_12,LINE_ICD9_DGNS_CD_13
971667,3386BF71A5F9DC65,19800601,NaN,M,0,24,12,12,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992256,348D8477213AE17D,19380901,NaN,F,Y,45,12,12,12,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
911208,3043020E68CB5A5D,19321101,NaN,F,0,42,12,12,0,12,...,71514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
benef2_claims = claims2.rename(columns={'DESYNPUF_ID':'bene_id'})
benef2_claims = benef.merge(right=benef2_claims, on='bene_id', how='left')
benef2_claims.sample(3)

,bene_id,birth_dt,death_dt,sex,esrd,state,hi_mos,smi_mos,hmo_mos,plan_mos,...,LINE_ICD9_DGNS_CD_4,LINE_ICD9_DGNS_CD_5,LINE_ICD9_DGNS_CD_6,LINE_ICD9_DGNS_CD_7,LINE_ICD9_DGNS_CD_8,LINE_ICD9_DGNS_CD_9,LINE_ICD9_DGNS_CD_10,LINE_ICD9_DGNS_CD_11,LINE_ICD9_DGNS_CD_12,LINE_ICD9_DGNS_CD_13
662237,A04247BD5BA69770,19270701,NaN,F,0,36,12,12,0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205902,873D8FA532CC8F75,19310601,NaN,F,0,33,12,12,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2390295,FD6A3DF062DA5C5E,19230901,NaN,F,0,49,12,12,0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN